name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      - name: Install dependencies for frontend and backend
        run: npm install

      - name: Install Nx CLI
        run: npm install -g nx

      - name: Check Nx installation
        run: nx --version


      - name: Build frontend (Angular)
        run: nx run TulpReizen2-web:build

      - name: Build backend (Nest.js)
        run: nx run data-api:build

      - name: Zip frontend artifacts for deployment
        run: |
          cd ${GITHUB_WORKSPACE}/dist/apps/TulpReizen2-web/ && zip ${GITHUB_WORKSPACE}/frontend-app-release.zip ./* -r

      - name: Zip backend artifacts for deployment
        run: |
          cd ${GITHUB_WORKSPACE}/dist/apps/data-api/ && zip ${GITHUB_WORKSPACE}/backend-api-release.zip ./* -r

      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: frontend-app-release.zip

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: backend-api
          path: backend-api-release.zip

  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend-app

      - name: Unzip frontend artifact
        run: unzip frontend-app-release.zip

      - name: Deploy to Azure Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (e.g., PR comments)
          action: "upload"
          app_location: "/" # App source code path for Angular
          api_location: "" # No API in the static web app
          output_location: "" # Location of built app content (optional)

  deploy-backend-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend-api

      - name: Unzip backend artifact
        run: unzip backend-api-release.zip

      - name: Install backend dependencies
        run: npm install

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TulpReizen2' # Replace with your backend app name in Azure
          slot-name: 'Production' # Slot for production, or change if using another slot
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }} # Add your publish profile secret
          package: .
