name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip apps from /dist
    steps:
      - uses: actions/checkout@v4

      - name: Debug workspace structure
        run: |
          echo "Current workspace: ${GITHUB_WORKSPACE}"
          echo "Workspace contents:"
          ls -R ${GITHUB_WORKSPACE}

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd ${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip artifacts for deployment
        run: |
          echo "Zipping data-api..."
          if [ -d "${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2/apps/data-api" ]; then
            cd ${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2/apps/data-api
            zip ${GITHUB_WORKSPACE}/data-api-release.zip ./* -r
          else
            echo "Directory ${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2/apps/data-api does not exist."
            exit 1
          fi

          echo "Zipping Angular app..."
          if [ -d "${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2/dist/apps/TulpReizen2-web" ]; then
            cd ${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2/dist/apps/TulpReizen2-web
            zip ${GITHUB_WORKSPACE}/TulpReizen2-web-release.zip ./* -r
          else
            echo "Directory ${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2/dist/apps/TulpReizen2-web does not exist."
            exit 1
          fi

      - name: Upload TulpReizen2 artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: TulpReizen2
          path: TulpReizen2-web-release.zip

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: data-api
          path: data-api-release.zip

  deploy-TulpReizen2:
    runs-on: ubuntu-latest
    name: Deploy Angular Frontend
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: TulpReizen2

      - name: Unzip artifact for deployment
        run: unzip TulpReizen2-web-release.zip

      - name: Deploy to static azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist/apps/TulpReizen2' # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}

  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJs data-api backend
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip

      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/Users/mikai/WebstormProjects/TulpReizen2/TulpReizen2/apps/data-api
          npm install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tulpreizen2-data-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.DATA_API_PUBLISHPROFILE }}
          package: .
